### ISSUE TITLE
Bug: Mention in `/assign` command does not ping the user

### ISSUE THREAD

**Issue by alexng353** [flatypus/discord-pushup-tracker#3]
![image](https://github.com/flatypus/discord-pushup-tracker/assets/26424336/e836f3e6-adc3-4a6a-8479-30ab295f1f7a)

#1 Doesn't actually mention the user. Apparently, this is because mentions have to be in the message component of the reply, not the embed.

**Comment by flatypus** [comment]
i hate discord
